### ISSUE TITLE
cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by degendeveloperatwork** [lazyc97/emo-clash#1]
I modified your json file to have

 "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
     "start": "npm run build",
  }
So that I could run build and it created me the www folder. I know wanted to launch the files and I get a message that : 
 cordova.js Failed to load resource: net::ERR_FILE_NOT_FOUND

How do you run this app, do you use Angular cli ? If so what version?

**Comment by nghduc97** [comment]
To build this require you to create `src/services/api-keys.ts` that export API keys for Microsoft Emotion API and Firebase web config object. Both provide free tier service so you can go to their websites and have a look.

Mine looks like this
``` typescript
export class ApiKeys {

  static MicrosoftEmotion = 'your-key';

  static FirebaseConfig = {
    apiKey: "...",
    authDomain: "emo-clash.firebaseapp.com",
    databaseURL: "https://emo-clash.firebaseio.com",
    storageBucket: "emo-clash.appspot.com",
    messagingSenderId: "..."
  };
}
```

**Comment by nghduc97** [comment]
I made this project out of hobby at first but got busy and left it for a while, so there are no instructions. If you're interested then sorry 'bout that.

**Comment by degendeveloperatwork** [comment]
thank you lazyc97, I am on the same path, trying to get my head around as started to become passionate about Microsoft emotion api. The api keys i understood, but two things that I am trying to understand as I am not familiar with firebase, I don't understand if you need to build a structure on firebase and what time type of structure and two why I got the cordova file missing and what could I be missing as If I put it manually it does not work :( But that you for looking into this anyway.
Are you available for freelance by any chance?

**Comment by nghduc97** [comment]
I'm an university student.
Firebase offers great free-tier service for a backend, so I don't need to write any server-side code but can still sync data across devices.
